######################################################################
# Automatically generated by qmake (3.0) Tue Jul 29 14:21:11 2014
######################################################################

TEMPLATE = app
TARGET = test1
CONFIG += qt 
INCLUDEPATH += .
DESTDIR=bin
CURBUILD=debug

CONFIG(debug, debug|release) {
    OBJECTS_DIR=obj/debug
    message("Debug build in progress....!")
} else {
    OBJECTS_DIR=obj/release
    message("Release build in progress....!")
}

# Input
SOURCES += src/main.cpp
